# MatRepr NumPy

Compare the native NumPy repr with MatRepr's formatting.

In [1]:
import numpy as np
np.random.seed(123)

# so matrepr can be imported from the source tree.
import sys
sys.path.insert(0, '..')

from matrepr import mdisplay, mprint

### 1D vector

In [2]:
v1 = np.arange(10, 50)
print(v1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
mdisplay(v1)

### A small 2D matrix

In [4]:
mat = np.random.random((10, 10))
print(mat)

[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
  0.9807642  0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426 0.73799541
  0.18249173 0.17545176 0.53155137 0.53182759]
 [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338 0.32295891
  0.36178866 0.22826323 0.29371405 0.63097612]
 [0.09210494 0.43370117 0.43086276 0.4936851  0.42583029 0.31226122
  0.42635131 0.89338916 0.94416002 0.50183668]
 [0.62395295 0.1156184  0.31728548 0.41482621 0.86630916 0.25045537
  0.48303426 0.98555979 0.51948512 0.61289453]
 [0.12062867 0.8263408  0.60306013 0.54506801 0.34276383 0.30412079
  0.41702221 0.68130077 0.87545684 0.51042234]
 [0.66931378 0.58593655 0.6249035  0.67468905 0.84234244 0.08319499
  0.76368284 0.24366637 0.19422296 0.57245696]
 [0.09571252 0.88532683 0.62724897 0.72341636 0.01612921 0.59443188
  0.55678519 0.15895964 0.15307052 0.69552953]
 [0.31876643 0.6919703  0.55438325 0.38895057 0.92513249 0.84167
  0.35739757 0.

In [5]:
mdisplay(mat, floatfmt=".4f")

### A 4D matrix

In [6]:
dense_4d = np.random.random((1000, 4, 4, 4))
mdisplay(dense_4d, floatfmt=".2f", max_rows=10)

### A big 2D matrix

In [7]:
big_2D = np.random.random_sample((100, 100))
print(big_2D)

[[0.56897491 0.24869477 0.23282594 ... 0.21161221 0.66903464 0.08251657]
 [0.12299359 0.27387659 0.27787458 ... 0.8907579  0.12631836 0.67237412]
 [0.95737435 0.89307959 0.337757   ... 0.24244685 0.5881787  0.26390893]
 ...
 [0.47967836 0.19472549 0.25491632 ... 0.00531315 0.02790694 0.83464496]
 [0.8427453  0.42523669 0.52167786 ... 0.44991197 0.37039488 0.56834534]
 [0.87152284 0.13423159 0.80242772 ... 0.91821905 0.41780322 0.43819597]]


In [8]:
mdisplay(big_2D)