# MatRepr numpy

In [1]:
import numpy as np
np.random.seed(123)

# so matrepr can be imported from the source tree.
import sys
sys.path.insert(0, '..')

from matrepr import mdisplay

## NumPy

Compare:

 * numpy's native `str`
 * MatRepr `str`
 * MatRepr HTML
 * MatRepr LaTeX

In [2]:
def render_all(mat):
    print(f"shape: {mat.shape}")
    print(mat)
    mdisplay(mat, "str", txt_width=100)
    mdisplay(mat, "html")
    mdisplay(mat, "latex")

#### A long vector

In [3]:
v1 = np.arange(10, 50)
render_all(v1)

shape: (40,)
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


length=40, 40 'int64' elements, array
  0    1    2    3    4    5    6         34    35    36    37    38    39
[10   11   12   13   14   15   22   ...   44    45    46    47    48    49 ]

<IPython.core.display.Latex object>

#### A small 2D matrix

In [4]:
a1 = np.array([[1, 2], [3, 4]])
render_all(a1)

shape: (2, 2)
[[1 2]
 [3 4]]


2×2, 4 'int64' elements, array
     0     1
  ┌           ┐
0 │  1     2  │
1 │  3     4  │
  └           ┘

<IPython.core.display.Latex object>

#### A small 3D matrix

In [5]:
a2 = np.array([
    [[1, 2], [3, 4]],
    [[10, 20], [30, 40]],
])
render_all(a2)

shape: (2, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[10 20]
  [30 40]]]


shape=(2,2,2), 8 'int64' elements, array
       0         1
  ┌                   ┐
0 │  [1 2]     [3 4]  │
1 │ [10 20]   [30 40] │
  └                   ┘

<IPython.core.display.Latex object>

#### A small 4D matrix

In [6]:
shape = (4,3,2,1)
a3 = np.arange(np.prod(shape)).reshape(shape)
render_all(a3)

shape: (4, 3, 2, 1)
[[[[ 0]
   [ 1]]

  [[ 2]
   [ 3]]

  [[ 4]
   [ 5]]]


 [[[ 6]
   [ 7]]

  [[ 8]
   [ 9]]

  [[10]
   [11]]]


 [[[12]
   [13]]

  [[14]
   [15]]

  [[16]
   [17]]]


 [[[18]
   [19]]

  [[20]
   [21]]

  [[22]
   [23]]]]


shape=(4,3,2,1), 24 'int64' elements, array
         0             1             2
  ┌                                         ┐
0 │  [[0] [1]]     [[2] [3]]     [[4] [5]]  │
1 │  [[6] [7]]     [[8] [9]]    [[10] [11]] │
2 │ [[12] [13]]   [[14] [15]]   [[16] [17]] │
3 │ [[18] [19]]   [[20] [21]]   [[22] [23]] │
  └                                         ┘

<IPython.core.display.Latex object>

In [7]:
r_4d = np.random.random_sample((2, 2, 2, 2))
render_all(r_4d)

shape: (2, 2, 2, 2)
[[[[0.69646919 0.28613933]
   [0.22685145 0.55131477]]

  [[0.71946897 0.42310646]
   [0.9807642  0.68482974]]]


 [[[0.4809319  0.39211752]
   [0.34317802 0.72904971]]

  [[0.43857224 0.0596779 ]
   [0.39804426 0.73799541]]]]


shape=(2,2,2,2), 16 'float64' elements, array
  
  ┌     ┐
0 │ ... │
1 │ ... │
  └     ┘

<IPython.core.display.Latex object>

#### A big 2D matrix

In [8]:
big_2D = np.random.random_sample((100, 100))
render_all(big_2D)

shape: (100, 100)
[[0.18249173 0.17545176 0.53155137 ... 0.82911263 0.33867085 0.55237008]
 [0.57855147 0.52153306 0.00268806 ... 0.78818717 0.41156922 0.48102628]
 [0.18162884 0.3213189  0.845533   ... 0.41862686 0.45308892 0.93235066]
 ...
 [0.50410699 0.56633121 0.85792438 ... 0.71670244 0.82622255 0.44210097]
 [0.53520708 0.23358017 0.33966677 ... 0.70903058 0.87831424 0.38683206]
 [0.42822551 0.89005017 0.04675397 ... 0.18451346 0.90837483 0.04621222]]


100×100, 10000 'float64' elements, array
       0        1         2          3              97        98        99
   ┌                                                                          ┐
 0 │ 0.1825   0.1755    0.5316    0.2937    ...   0.8291    0.3387    0.5524  │
 1 │ 0.5786   0.5215   0.002688    0.807    ...   0.7882    0.4116     0.481  │
 2 │ 0.1816   0.3213    0.8455    0.3137    ...   0.4186    0.4531    0.9324  │
 3 │ 0.5875   0.9483    0.556     0.02661   ...   0.6177    0.3689     0.612  │
 4 │ 0.2061   0.1651    0.3618    0.6559    ...   0.3034    0.3398    0.5951  │
   │   :        :         :          :      ...     :         :          :    │
95 │ 0.9905   0.6927    0.4909    0.9723    ...   0.5128    0.6353    0.7554  │
96 │ 0.4565   0.606     0.2688    0.9039    ...   0.4215   0.006212   0.8734  │
97 │ 0.5041   0.5663    0.8579    0.8407    ...   0.7167    0.8262    0.4421  │
98 │ 0.5352   0.2336    0.3397     0.105    ...   0.709     0.8783    0.3868  │
99 │

<IPython.core.display.Latex object>

## Jupyter formatting

In [9]:
v1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
a1

array([[1, 2],
       [3, 4]])

In [11]:
a2

array([[[ 1,  2],
        [ 3,  4]],

       [[10, 20],
        [30, 40]]])

## More compact size

In [12]:
import matrepr
matrepr.params.max_rows = 10
matrepr.params.max_cols = 7
matrepr.params.num_after_dots = 0
matrepr.params.indices = False

In [13]:
render_all(v1)

shape: (40,)
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


length=40, 40 'int64' elements, array
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 34, ...]

<IPython.core.display.Latex object>

In [14]:
render_all(big_2D)

shape: (100, 100)
[[0.18249173 0.17545176 0.53155137 ... 0.82911263 0.33867085 0.55237008]
 [0.57855147 0.52153306 0.00268806 ... 0.78818717 0.41156922 0.48102628]
 [0.18162884 0.3213189  0.845533   ... 0.41862686 0.45308892 0.93235066]
 ...
 [0.50410699 0.56633121 0.85792438 ... 0.71670244 0.82622255 0.44210097]
 [0.53520708 0.23358017 0.33966677 ... 0.70903058 0.87831424 0.38683206]
 [0.42822551 0.89005017 0.04675397 ... 0.18451346 0.90837483 0.04621222]]


100×100, 10000 'float64' elements, array
┌                                                                            ┐
│ 0.1825    0.1755    0.5316    0.5318     0.6344    0.8494    0.624     ... │
│ 0.5786    0.5215   0.002688   0.9883     0.9053    0.2076   0.09333    ... │
│ 0.1816    0.3213    0.8455    0.1869     0.4173    0.989    0.005545   ... │
│ 0.5875    0.9483    0.556     0.5006    0.003532   0.4809    0.9377    ... │
│ 0.2061    0.1651    0.3618    0.8634     0.5094    0.2969    0.4235    ... │
│ 0.4413    0.9328    0.3976    0.4778     0.6172    0.4047    0.2475    ... │
│ 0.2986    0.9418    0.9088     0.162     0.9811    0.7507   0.09818    ... │
│ 0.04357   0.684     0.1961    0.02734    0.551     0.8133    0.769     ... │
│ 0.2207    0.294     0.8285    0.3673    0.08335    0.1963    0.7516    ... │
│    :        :         :          :         :         :         :       ... │
└                                                                            ┘

<IPython.core.display.Latex object>