# MatRepr TensorFlow

Neatly format dense `tf.Tensor` and sparse `tf.SparseTensor`.

1D dense and sparse tensors are formatted as row vectors.

2D dense and sparse tensors are formatted as matrices.

3D+ sparse tensors are formatted as a list of index/value tuples. Dense 3D+ tensors rendered with native TensorFlow formatter.

In [1]:
import tensorflow as tf

tf.random.set_seed(1234)

# so matrepr can be imported from the source tree.
import sys
sys.path.insert(0, '..')

from matrepr import mdisplay, mprint

In [2]:
scalar = tf.constant(5)

dense1D = tf.random.uniform(shape=(5000,))

rand2D = tf.random.uniform(shape=(128, 64)).numpy()
rand2D[rand2D < 0.6] = 0
rand2D_sparse = tf.sparse.from_dense(tf.convert_to_tensor(rand2D))

small3D = tf.constant([[[1., 0], [2., 3.]], [[4., 0], [5., 6.]]])
coo3D = tf.sparse.from_dense(small3D)

In [3]:
dense1D

<tf.Tensor: shape=(5000,), dtype=float32, numpy=
array([0.5380393 , 0.36461866, 0.5816301 , ..., 0.5440619 , 0.8671317 ,
       0.5084995 ], dtype=float32)>

In [4]:
rand2D_sparse

SparseTensor(indices=tf.Tensor(
[[  0   2]
 [  0   6]
 [  0   7]
 ...
 [127  44]
 [127  45]
 [127  46]], shape=(3304, 2), dtype=int64), values=tf.Tensor([0.64804935 0.7057973  0.7185966  ... 0.79349816 0.85203743 0.95652413], shape=(3304,), dtype=float32), dense_shape=tf.Tensor([128  64], shape=(2,), dtype=int64))

In [5]:
coo3D

SparseTensor(indices=tf.Tensor(
[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]], shape=(6, 3), dtype=int64), values=tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32), dense_shape=tf.Tensor([2 2 2], shape=(3,), dtype=int64))

In [6]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

## MatRepr default

Load the MatRepr Jupyter extension with `%load_ext matrepr` to render tensors with MatRepr by default.

A single-use alternative is to use `matrepr.mdisplay()`. For console use `matrepr.mprint()`. 

In [7]:
%load_ext matrepr

In [8]:
dense1D

<tf.Tensor: shape=(5000,), dtype=float32, numpy=
array([0.5380393 , 0.36461866, 0.5816301 , ..., 0.5440619 , 0.8671317 ,
       0.5084995 ], dtype=float32)>

In [9]:
rand2D_sparse

SparseTensor(indices=tf.Tensor(
[[  0   2]
 [  0   6]
 [  0   7]
 ...
 [127  44]
 [127  45]
 [127  46]], shape=(3304, 2), dtype=int64), values=tf.Tensor([0.64804935 0.7057973  0.7185966  ... 0.79349816 0.85203743 0.95652413], shape=(3304,), dtype=float32), dense_shape=tf.Tensor([128  64], shape=(2,), dtype=int64))

In [10]:
coo3D

SparseTensor(indices=tf.Tensor(
[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]], shape=(6, 3), dtype=int64), values=tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32), dense_shape=tf.Tensor([2 2 2], shape=(3,), dtype=int64))

In [11]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

# Labels

Specify title, row and/or column labels to help the reader quickly understand what they are looking at.

In [12]:
dense = tf.random.uniform(shape=(64, 32)).numpy()
dense[dense < 0.3] = 0
tensor = tf.sparse.from_dense(tf.convert_to_tensor(dense))

obs_labels = [f"observation {i}" for i in range(tensor.shape[0])]  # list of labels
feature_labels = {i: f"feature {i+1}" for i in range(tensor.shape[1])}  # map index to label works too

In [13]:
mdisplay(tensor, row_labels=obs_labels, col_labels=feature_labels, title="Random Dataset")

## LaTeX

In [14]:
mdisplay(rand2D_sparse, "latex")

<IPython.core.display.Latex object>

## String

In [15]:
mprint(rand2D_sparse)

<128×64, 3304 '<dtype: 'float32'>' elements, tf.SparseTensor>
        0       1       2       3            60      61      62      63
    ┌                                                                     ┐
  0 │                 0.648           ...                  0.8016         │
  1 │                         0.6572  ...          0.8348  0.6638  0.735  │
  2 │                                 ...          0.8845          0.6323 │
  3 │ 0.7025          0.8244  0.9619  ...  0.7132  0.6676  0.7929         │
  4 │ 0.9482  0.7316                  ...  0.656   0.9197                 │
    │   :       :       :       :     ...    :       :       :       :    │
123 │         0.8794                  ...                                 │
124 │ 0.9892  0.8918          0.8262  ...  0.9966          0.6415         │
125 │                 0.7946          ...                          0.6766 │
126 │         0.9059  0.8707          ...  0.9893  0.7788  0.7175  0.6775 │
127 │         0.9523  0.6485  

## More compact size

In [16]:
import matrepr
matrepr.params.max_rows = 10
matrepr.params.max_cols = 7
matrepr.params.num_after_dots = 0

In [17]:
rand2D_sparse

SparseTensor(indices=tf.Tensor(
[[  0   2]
 [  0   6]
 [  0   7]
 ...
 [127  44]
 [127  45]
 [127  46]], shape=(3304, 2), dtype=int64), values=tf.Tensor([0.64804935 0.7057973  0.7185966  ... 0.79349816 0.85203743 0.95652413], shape=(3304,), dtype=float32), dense_shape=tf.Tensor([128  64], shape=(2,), dtype=int64))